services:
  # API 1: (Spring Boot)
  api-spring:
    build:
      context: https://github.com/VitorMalacarne/SpringBoot_sistema-monitoramento.git
    container_name: api_spring
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - ./.env.local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d monitoramento"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
    networks:
      - appnet

  # API 2: (Express)
  api-express:
    build:
      context: https://github.com/VitorMalacarne/Express_api-leituras.git
    container_name: api_express
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://root:123456@mongo:27017/leiturasdb?authSource=admin
    env_file:
      - ./.env.local
    depends_on:
      - mongo
    networks:
      - appnet
    restart: always

  # Front-end Web
  front-web:
    build:
      context: https://github.com/VitorMalacarne/tac_app_front_end.git
    container_name: front_web
    expose:
      - "80"
    env_file:
      - ./.env.local
    networks:
      - appnet

  # NGINX (API Gateway)
  nginx:
    image: nginx:latest
    container_name: api_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api-spring
      - api-express
      - front-web
    networks:
      - appnet

  # --- Banco MongoDB ---
  mongo:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - appnet

  # --- Banco PostgreSQL ---
  postgres:
    image: postgres:15
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_DB: monitoramento
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

volumes:
  mongo_data:
  postgres_data:

networks:
  appnet:
    driver: bridge
